version: "3.8"

services:
  lpcoutinho-web:
    image: lpcoutinho-web:latest  
    volumes:
      - lpcoutinho-data:/app/data
      - lpcoutinho-static:/app/staticfiles
      - lpcoutinho-media:/app/media
      - lpcoutinho-logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - SECRET_KEY=your-secret-key-here-change-me
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - MeteNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.lpcoutinho.rule=Host(`lpcoutinho.top`) || Host(`www.lpcoutinho.top`)
        - traefik.http.routers.lpcoutinho.entrypoints=websecure
        - traefik.http.routers.lpcoutinho.tls.certresolver=letsencryptresolver
        - traefik.http.services.lpcoutinho.loadbalancer.server.port=8000
        - traefik.http.services.lpcoutinho.loadbalancer.passHostHeader=true
        - traefik.http.routers.lpcoutinho.service=lpcoutinho
        # Redirect www to non-www
        - traefik.http.routers.lpcoutinho.middlewares=www-redirect
        - traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\.(.*)
        - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}
        - traefik.http.middlewares.www-redirect.redirectregex.permanent=true

networks:
  MeteNet:
    external: true
    name: MeteNet

volumes:
  lpcoutinho-data:
    external: true
    name: lpcoutinho-data
  lpcoutinho-static:
    external: true
    name: lpcoutinho-static
  lpcoutinho-media:
    external: true
    name: lpcoutinho-media
  lpcoutinho-logs:
    external: true
    name: lpcoutinho-logs