version: "3.8"

services:
  lpcoutinho-web:
    image: lpcoutinho-web:latest  
    command: sh -c "python manage.py migrate --settings=config.settings.prod && python manage.py collectstatic --noinput --settings=config.settings.prod && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
    volumes:
      - /root/lpcoutinho:/app    
      - lpcoutinho-static:/app/staticfiles
      - lpcoutinho-media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - SECRET_KEY=your-secret-key-here-change-me
    ports:
      - "8000:8000"
    networks:
      - MeteNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.lpcoutinho.rule=Host(`lpcoutinho.top`) || Host(`www.lpcoutinho.top`)
        - traefik.http.routers.lpcoutinho.entrypoints=websecure
        - traefik.http.routers.lpcoutinho.tls.certresolver=letsencryptresolver
        - traefik.http.services.lpcoutinho.loadbalancer.server.port=8000
        - traefik.http.services.lpcoutinho.loadbalancer.passHostHeader=true
        - traefik.http.routers.lpcoutinho.service=lpcoutinho
        # Redirect www to non-www
        - traefik.http.routers.lpcoutinho.middlewares=www-redirect
        - traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\.(.*)
        - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}
        - traefik.http.middlewares.www-redirect.redirectregex.permanent=true

networks:
  MeteNet:
    external: true
    name: MeteNet

volumes:
  lpcoutinho-static:
    external: true
    name: lpcoutinho-static
  lpcoutinho-media:
    external: true
    name: lpcoutinho-media