# Generated by Django 5.2.2 on 2026-04-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(help_text='Emoji ou nome do ícone', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField(help_text='O texto completo do prompt')),
                ('descricao_curta', models.CharField(blank=True, help_text='Descrição breve para preview', max_length=300)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na categoria')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem de exemplo (opcional)', null=True, upload_to='biblioteca_ia/prompts/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='biblioteca_ia.categoria')),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'ordering': ['categoria', 'ordem', 'titulo'],
            },
        ),
    ]
