# Generated by Django 5.2.2 on 2026-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='como_usar',
            field=models.TextField(blank=True, help_text='Como usar o prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='exemplo_resultado',
            field=models.TextField(blank=True, help_text='Exemplo de resultado'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='para_que_serve',
            field=models.TextField(blank=True, help_text='Para que serve este prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='resultado_esperado',
            field=models.TextField(blank=True, help_text='Resultado esperado'),
        ),
    ]
