# Generated by Django 5.2.2 on 2025-06-07 12:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatorresult',
            name='pj_outros_gastos',
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='clt_anos_empresa',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Anos na Empresa'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='clt_incluir_fgts',
            field=models.BooleanField(default=True, verbose_name='Incluir FGTS'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='clt_outros_descontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Outros Descontos'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='clt_pensao_alimenticia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pensão Alimentícia'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='pj_beneficios_nao_tributaveis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Benefícios Não-Tributáveis'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='pj_beneficios_tributaveis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Benefícios Tributáveis'),
        ),
        migrations.AddField(
            model_name='calculatorresult',
            name='pj_outras_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Outras Despesas'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='clt_salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salário Bruto Mensal'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='clt_vale_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vale Refeição/Alimentação'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='clt_vale_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vale-Transporte'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='pj_contador',
            field=models.DecimalField(decimal_places=2, default=189, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Honorários Contador'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='pj_inss',
            field=models.DecimalField(decimal_places=2, default=166.98, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Contribuição INSS'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='pj_salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salário Bruto Mensal'),
        ),
        migrations.AlterField(
            model_name='calculatorresult',
            name='pj_taxa_imposto',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Alíquota de Impostos (%)'),
        ),
    ]
