# Generated by Django 5.2.2 on 2025-06-07 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('excerpt', models.TextField(help_text='Breve descrição do post (máx. 300 caracteres)', max_length=300, verbose_name='Resumo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula (ex: django, python, ai)', max_length=200)),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'verbose_name_plural': 'Posts do Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
